services: docker

env:
  - distro: rhel7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    ansible_opts: |
      -e /etc/ansible/roles/role_under_test/tests/extra_vars.yml
      -t ''
      --skip-tags ''

before_install:
  # Pull container.
  - 'docker pull samdoran/${distro}-ansible:latest'

script:
  - container_id=$(mktemp)

  # Run container in detached state.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} samdoran/${distro}-ansible:latest "${init}" > "${container_id}"'

  # Install dependencies
  #- 'docker exec "$(cat ${container_id})" ansible-galaxy install -r /etc/ansible/roles/role_under_test/tests/requirements.yml'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --syntax-check'

  # Test role.
  - 'docker exec "$(cat ${container_id})" ansible-playbook $ansible_opts /etc/ansible/roles/role_under_test/tests/travis.yml'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook $ansible_opts /etc/ansible/roles/role_under_test/tests/travis.yml tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
