---
sudo: required
services: docker
dist: xenial
language: python
python:
  - 3.7
jobs:
  include:
  - name: "AWS Test"
    if: fork IS false
    env: TYPE=aws
  - name: "Docker Test"
    env: TYPE=docker
before_install:
  - |
    if [ "${TYPE}" == "docker" ]; then
      docker pull centos/systemd
      if [[ "${TRAVIS_PULL_REQUEST}" == "false" || "${TRAVIS_PULL_REQUEST_SLUG}" == "MindPointGroup/RHEL7-STIG" ]]; then
        docker pull registry.access.redhat.com/rhel7:latest
        (cd tests/docker; docker build --build-arg rhn_user=$RHN_USERNAME --build-arg rhn_pass=$RHN_PASSWORD -t  molly .)
      else
        sed -i '/- name: RHEL/,/- docker/d' ./molecule/docker/molecule.yml
      fi
    fi
install:
  - pip3 install -r tests/ci-requirements.txt
script:
  - molecule --base-config base-molecule.yml test --scenario-name $TYPE
