- block:
    - name: "HIGH | RHEL-07-010010 | AUDIT | The file permissions, ownership, and group membership of system files and commands must match the vendor values."
      shell: 'rpm -Va | grep ''^.M'''
      args:
        warn: no
      check_mode: no
      failed_when: no
      changed_when: no
      ignore_errors: yes
      register: rhel_07_010010_audit

    - name: "HIGH | RHEL-07-010010 | PATCH | The file permissions, ownership, and group membership of system files and commands must match the vendor values."
      shell: 'rpm --setperms $(rpm -qf {{ item.split('' '')[-1] }}); rpm --setugids $(rpm -qf {{ item.split('' '')[-1] }})'
      with_items: "{{ rhel_07_010010_audit.stdout_lines }}"
      when: rhel_07_010010_audit.stdout_lines | length > 0
  when: rhel_07_010010
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-010010

- block:
    - name: "HIGH | RHEL-07-010020 | AUDIT | The cryptographic hash of system files and commands must match vendor values."
      shell: 'rpm -Va | grep ''^..5'' | grep -E ''/.?bin/'''
      args:
          warn: no
      check_mode: no
      failed_when: no
      changed_when: no
      ignore_errors: yes
      register: rhel_07_010020_audit

    - name: "HIGH | RHEL-07-010020 | PATCH | The cryptographic hash of system files and commands must match vendor values."
      shell: yum reinstall -y $(rpm -qf {{ item.split(' ')[-1] }})
      with_items: "{{ rhel_07_010020_audit.stdout_lines }}"
      ignore_errors: yes
      when: rhel_07_010020_audit.stdout_lines | length > 0
  when: rhel_07_010020
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-010020

- name: "HIGH | RHEL-07-010290 | PATCH | The system must not have accounts configured with blank or null passwords."
  replace:
      dest: /etc/pam.d/system-auth
      follow: true
      regexp: 'nullok ?'
  when: rhel_07_010290
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-010290

- name: "HIGH | RHEL-07-010300 | PATCH | The SSH daemon must not allow authentication using an empty password."
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: ^#?PermitEmptyPasswords
      line: PermitEmptyPasswords no
      validate: sshd -tf %s
  notify: restart sshd
  when: rhel_07_010300
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-010300
      - sshd

- name: "HIGH | RHEL-07-010440 | PATCH | The operating system must not allow an unattended or automatic logon to the system."
  lineinfile:
      dest: /etc/gdm/custom.conf
      regexp: (?i)automaticloginenable
      line: AutomaticLoginEnable=false
      insertafter: '\[daemon\]'
  when:
      - rhel7stig_gui
      - rhel_07_010440
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-010440
      - gui

- name: "HIGH | RHEL-07-010450 | PATCH | The operating system must not allow an unrestricted logon to the system."
  lineinfile:
      dest: /etc/gdm/custom.conf
      regexp: (?i)timedloginenable
      line: TimedLoginEnable=false
      insertafter: '\[daemon\]'
  when:
      - rhel7stig_gui
      - rhel_07_010450
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-010450


- name: |

      "HIGH | RHEL-07-010480 | PATCH | Systems with a Basic Input/Output System (BIOS) must require authentication upon booting into single-user and maintenance modes."
      "HIGH | RHEL-07-010490 | PATCH | Systems using Unified Extensible Firmware Interface (UEFI) must require authentication upon booting into single-user and maintenance modes."
  lineinfile:
      dest: /etc/grub.d/40_custom
      insertafter: EOF
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  with_items: "{{ rhel7stig_boot_password_config }}"
  notify: make grub2 config
  when: rhel_07_010480 or rhel_07_010490
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-010480
      - RHEL-07-010490
      - grub
      - bootloader

- name: "HIGH | RHEL-07-020000 | PATCH | The rsh-server package must not be installed"
  yum:
      name: rsh-server
      state: absent
  when: rhel_07_020000
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020000
      - rsh

- name: "HIGH | RHEL-07-020010 | PATCH | The ypserv package must not be installed."
  yum:
     name: ypserv
     state: absent
  when: rhel_07_020010
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020010
      - ypserv

- name: "HIGH | RHEL-07-020050 | PATCH | The operating system must prevent the installation of software, patches, service packs, device drivers, or operating system components from a repository without verification they have been digitally signed using a certificate that is issued by a Certificate Authority (CA) that is recognized and approved by the organization."
  lineinfile:
      dest: /etc/yum.conf
      regexp: gpgcheck
      line: gpgcheck=1
      insertafter: '\[main\]'
  when: rhel_07_020050
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020050
      - yum

- name: "HIGH | RHEL-07-020060 | PATCH | The operating system must prevent the installation of software, patches, service packs, device drivers, or operating system components of local packages without verification they have been digitally signed using a certificate that is issued by a Certificate Authority (CA) that is recognized and approved by the organization."
  lineinfile:
      dest: /etc/yum.conf
      regexp: localpkg_gpgcheck
      line: localpkg_gpgcheck=1
      insertafter: '\[main\]'
  when: rhel_07_020060
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020060
      - yum

- name: "HIGH | RHEL-07-020070 | PATCH | The operating system must prevent the installation of software, patches, service packs, device drivers, or operating system components of packages without verification of the repository metadata."
  lineinfile:
      dest: /etc/yum.conf
      regexp: repo_gpgcheck
      line: repo_gpgcheck=1
      insertafter: '\[main\]'
  when: rhel_07_020070
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020070
      - yum

- name: |

      "HIGH | RHEL-07-020210 | PATCH | The operating system must enable SELinux."
      "HIGH | RHEL-07-020220 | PATCH | The operating system must enable the SELinux targeted policy."
  selinux:
      state: enforcing
      policy: targeted
  when: rhel_07_020210 or rhel_07_020220
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020210
      - RHEL-07-020220
      - selinux

# The fix in the STIG for this is incorrect. Symlinking this unit file to /dev/null obtains the required result
# which is to disable this function and log when the keystroke is issued.
# https://access.redhat.com/solutions/1123873
- name: "HIGH | RHEL-07-020230 | PATCH | The x86 Ctrl-Alt-Delete key sequence must be disabled."
  file:
      src: /dev/null
      dest: /etc/systemd/system/ctrl-alt-del.target
      state: link
  when: rhel_07_020230
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020230

# RHEL-07-020250 | PATCH | The operating system must be a supported release."
# Not automated since current end of life for RHEL 7 is 2024-06-30

- block:
    # Currently just locks user account
    - name: "HIGH | RHEL-07-020310 | AUDIT | The root account must be the only account having unrestricted access to the system"
      shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}'"
      check_mode: no
      changed_when: no
      failed_when: no
      ignore_errors: yes
      register: rhel_07_020310_audit

    - name: "HIGH | RHEL-07-020310 | PATCH | The root account must be the only account having unrestricted access to the system"
      command: "passwd -l {{ item }}"
      with_items: "{{ rhel_07_020310_audit.stdout_lines }}"
      when: rhel_07_020310_audit.rc
  when: rhel_07_020310
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020310

- block:
    - name: "HIGH | RHEL-07-021350 | PATCH | The operating system must implement NIST FIPS-validated cryptography for the following: to provision digital signatures, to generate cryptographic hashes, and to protect unclassified information requiring confidentiality and cryptographic protection in accordance with applicable federal laws, Executive Orders, directives, policies, regulations, and standards."
      yum:
          name: dracut-fips
          state: present

    - name: "HIGH | RHEL-07-021350 | PATCH | The operating system must implement NIST FIPS-validated cryptography for the following: to provision digital signatures, to generate cryptographic hashes, and to protect unclassified information requiring confidentiality and cryptographic protection in accordance with applicable federal laws, Executive Orders, directives, policies, regulations, and standards."
      lineinfile:
          create: yes
          dest: /etc/sysconfig/prelink
          regexp: ^#?PRELINKING
          line: PRELINKING=no

    - name: "HIGH | RHEL-07-021350 | PATCH | Check if prelink package is installed"
      command: rpm -q prelink
      args:
          warn: no
      changed_when: no
      failed_when: no
      register: rhel_07_021350_prelink_installed

    - name: "HIGH | RHEL-07-021350 | PATCH | The operating system must implement NIST FIPS-validated cryptography for the following: to provision digital signatures, to generate cryptographic hashes, and to protect unclassified information requiring confidentiality and cryptographic protection in accordance with applicable federal laws, Executive Orders, directives, policies, regulations, and standards."
      command: prelink -ua
      when: rhel_07_021350_prelink_installed.rc == 0
  when: rhel_07_021350
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-021350

- name: "HIGH | RHEL-07-021710 | PATCH | The telnet-server package must not be installed."
  yum:
      name: telnet-server
      state: absent
  when: rhel_07_021710
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-021710
      - telnet

- block:
    - name: "HIGH | RHEL-07-030000 | PATCH | Auditing must be configured to produce records containing information to establish what type of events occurred, where the events occurred, the source of the events, and the outcome of the events. These audit records must also identify individual identities of group account users."
      yum:
          name: audit
          state: present

    - name: "HIGH | RHEL-07-030000 | PATCH | Auditing must be configured to produce records containing information to establish what type of events occurred, where the events occurred, the source of the events, and the outcome of the events. These audit records must also identify individual identities of group account users."
      service:
          name: auditd
          state: started
          enabled: yes
  when: rhel_07_030000
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-030000
      - auditd

- block:
    - name: "HIGH | RHEL-07-032000 | PATCH | The system must use a DoD-approved virus scan program."
      yum:
          name: "{{ rhel7stig_av_package.package }}"
          state: present

    - name: "HIGH | RHEL-07-032000 | PATCH | The system must use a DoD-approved virus scan program."
      service:
          name: "{{ rhel7stig_av_package.service }}"
          state: started
          enabled: yes
      ignore_errors: yes
  when:
      - rhel7stig_antivirus_required
      - rhel_07_032000
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-032000
      - antivirus

- name: "HIGH | RHEL-07-040390 | PATCH | The SSH daemon must be configured to only use the SSHv2 protocol."
  lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: (?i)^#?protocol
      line: Protocol 2
      validate: sshd -t -f %s
  notify: restart sshd
  when: rhel_07_040390
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040390
      - ssh

- block:
    - name: "HIGH | RHEL-07-040540 | AUDIT | There must be no .shosts files on the system."
      find:
          paths: /
          recurse: yes
          hidden: yes
          patterns: '*.shosts'
      check_mode: no
      register: rhel_07_040540_audit

    - name: "HIGH | RHEL-07-040540 | PATCH | There must be no .shosts files on the system."
      file:
          path: "{{ item.path }}"
          state: absent
      with_items: "{{ rhel_07_040540_audit.files }}"
  when: rhel_07_040540
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040540
      - shosts

- block:
    - name: "HIGH | RHEL-07-040550 | AUDIT | There must be no shosts.equiv files on the system."
      find:
          paths: /
          recurse: yes
          patterns: shosts.equiv
      check_mode: no
      register: rhel_07_040550_audit

    - name: "HIGH | RHEL-07-040550 | PATCH | There must be no shosts.equiv files on the system."
      file:
          path: "{{ item.path }}"
          state: absent
      with_items: "{{ rhel_07_040550_audit.files }}"
  when: rhel_07_040550
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040550
      - shosts

- name: "HIGH | RHEL-07-040690 | PATCH | A File Transfer Protocol (FTP) server package must not be installed unless needed."
  yum:
      name: lftpd
      state: absent
  when:
      - not rhel7stig_lftpd_required
      - rhel_07_040690
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040690
      - ftp

- name: "HIGH | RHEL-07-040700 | PATCH | The Trivial File Transfer Protocol (TFTP) server package must not be installed if not required for operational support."
  yum:
      name:
          - tftp
          - tftp-server
      state: absent
  when:
      - not rhel7stig_tftp_required
      - rhel_07_040700
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040700
      - tftp

- name: "HIGH | RHEL-07-040710 | PATCH | Remote X connections for interactive users must be encrypted."
  lineinfile:
      create: yes
      dest: /etc/ssh/sshd_config
      regexp: (?i)^#?x11forwarding
      line: X11Forwarding yes
      validate: sshd -t -f %s
  notify: restart sshd
  when: rhel_07_040710
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040710
      - ssh

- block:
    - name: "PRELIM | RHEL-07-040800 | AUDIT | SNMP community strings must be changed from the default."
      command: grep {{ item }} /etc/snmp/snmpd.conf
      check_mode: no
      failed_when: no
      changed_when: no
      ignore_errors: yes
      with_items:
          - public
          - private
      register: rhel_07_040800_audit

    - name: "HIGH | RHEL-07-040800 | PATCH | SNMP community strings must be changed from the default."
      replace:
          dest: /etc/snmp/snmpd.conf
          regexp: (^com2sec.*default\s+)(public|private)
          replace: \1{{ rhel7stig_snmp_community }}
      with_items: "{{ rhel_07_040800_audit.results }}"
      notify: restart snmpd
      when: item.stdout_lines | length > 0
  when: rhel_07_040800
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040800
      - snmp
