---
- name: restart sshd
  service:
      name: sshd
      state: restarted
  when:
      - not rhel7stig_system_is_chroot

- name: reboot system
  shell: sleep 3; reboot
  async: 15
  poll: 0

- name: restart snmpd
  service:
      name: snmpd
      state: restarted
  when:
      - not rhel7stig_system_is_chroot

- name: make grub2 config
  command: /usr/sbin/grub2-mkconfig --output={{ rhel7stig_grub_cfg_path }}
  when:
      - not rhel7stig_skip_for_travis
      - not rhel7stig_system_is_container

- name: "restart {{ rhel7stig_time_service }}"
  service:
      name: "{{ rhel7stig_time_service }}"
      state: restarted
  when:
      - not rhel7stig_system_is_chroot

- name: restart auditd
  command: /usr/sbin/service auditd restart
  args:
      warn: no
  when:
      - rhel7stig_skip_for_travis == false
      - not rhel7stig_system_is_chroot
      - not rhel7stig_system_is_container

- name: rebuild initramfs
  command: dracut -f

- name: undo existing prelinking
  command: prelink -ua

- name: update running audit failure mode
  command: auditctl -f {{ rhel7stig_auditd_failure_flag }}
  failed_when: no

- name: init aide and wait
  command: /usr/sbin/aide --init -B 'database_out=file:{{ rhel7stig_aide_temp_db_file }}'
  notify: move aide db

- name: init aide
  shell: nohup /usr/sbin/aide --init -B 'database_out=file:{{ rhel7stig_aide_temp_db_file }}' > /dev/null &
  notify: move aide db

- name: move aide db
  command: "mv {{ rhel7stig_aide_temp_db_file }} {{ rhel7stig_aide_db_file }}"
  when: not rhel7stig_aide_db_status.stat.exists or rhel7stig_overwrite_aide_db
