---
- name: Converge
  hosts: all
  pre_tasks:
    - name: install packages for testing under docker
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - selinux-policy
        - libselinux-python
        - openssh-server
        - which

    - name: Generate hostkey
      systemd:
        name: sshd
        state: started
        enabled: true


  roles:
    - role: RHEL7-STIG
      rhel7stig_system_is_container: yes

  post_tasks:
    - name: Check if rhel
      command: which subscription-manager
      ignore_errors: true
      changed_when: false
      register: sm

    - name: Deregister from RH
      redhat_subscription:
        state: absent
      when: not sm is failed
